// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ScrollingController from "./scrolling_controller"
application.register('scrolling', ScrollingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FadeinController from "./fadein_controller"
application.register("fadein", FadeinController)
